version: "3.7"
services:
  ## === mongo ===
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    networks:
      - net_common
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo/data:/data/

# 创建自定义网络
networks:
  net_common:
    driver: bridge